name: CI/CD for Dev Environment

on:
  push:
    branches:
    - feat/family


env:
  ENV: "dev"
  APP_NAME: image-app
  APP_IMAGE_NAME: image-app
  APP_IMAGE_TAG: dev
  REPOSITORY_URL: 
  REPOSITORY_NAME:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  CONTAINER_REGISTRY_PULL_SECRET: $ {{ secrete.QUAY_DOCKER_CONFIG_JSON_PULL_SECRET }}
  CONTAINER_REGISTRY: ${{secrets.CONTAINER_REGISTRY }} # user "docker.io" for docker hub


jobs:
  build:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
    -uses: actions/checkout@v2

    - name: Set up Python Environment
      uses: action/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Unit tests on the app
      run: |
        python -m py_compile app.py
    

